<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Emergency Alert Notification</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            color: #333;
            background-color: #f8f9fa;
            padding: 20px;
        }
        .container {
            background-color: #fff;
            border-left: 5px solid #dc3545;
            padding: 20px;
            max-width: 600px;
            margin: auto;
            box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        }
        h2 {
            color: #dc3545;
        }
        a {
            color: #007bff;
        }
        .footer {
            margin-top: 30px;
            font-size: 0.9em;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>🚨 Emergency Alert: {{ ucfirst($type) }}</h2>

        @if(!is_null($latitude) && !is_null($longitude))
            <p><strong>Location:</strong>
                <a href="https://www.google.com/maps?q={{ $latitude }},{{ $longitude }}" target="_blank">
                    Click here to view on Google Maps
                </a><br>
                <small>(Latitude: {{ $latitude }}, Longitude: {{ $longitude }})</small>
            </p>
        @endif

        @if(!empty($emergencyMessage))
            <p><strong>Message:</strong> {{ $emergencyMessage }}</p>
        @else
            <p><strong>Message:</strong> (No additional message provided)</p>
        @endif

        <div class="footer">
            This alert was automatically generated by the <strong>Smart Emergency Response Locator</strong> system.
        </div>
    </div>
</body>
</html>
